"""Vanilla customer data for Burger Shop 2, extracted from the game's XML files.

Generated from DefLevel_Test.xml (the <Customer> pools) and Game.xml (the story
level order).  Generation runs on machines without the game installed, so this
table -- not the game files -- is the source of truth for the character shuffle.
Regenerate it if the game ever ships new level data.
"""
from __future__ import annotations


# Characters whose presence in a level gates it behind an AP item: the item they
# want is moved off-screen (Coords.xml) until the player receives it, so the level
# cannot be completed.  Keyed by lowercased character name.
GATED_CHARACTERS: dict[str, str] = {
    "oldchap":  "Menu",
    "dogbag":   "Dog Biscuit",
    "annoying": "Shirt",
}

# Characters that keep their vanilla placement exactly and are never used as a
# replacement.  Empty for Burger Shop 2: unlike Burger Shop 1, no story level has a
# built-in alien requirement, so the Alien takes part in the shuffle like anyone else.
FROZEN_CHARACTERS: frozenset[str] = frozenset()

# <Customer> pools that must never draw a GATED_CHARACTERS entry.  It's
# theoretically possible for gated characters to be generated for all early
# levels, possibly making generation fail.  This ensures that level 1 contains
# no gated characters.  Vanilla already keeps these characters out of it.
UNGATED_CUSTOMER_IDS: frozenset[str] = frozenset({"customers1-1a"})

# Characters that can be shuffled *in* even though no vanilla pool contains them.
# Burger Shop 2 ships Breakfast/Order/Dinner_Alien.xml and a CustomerTimes entry for
# the Alien, but DefLevel_Test.xml never references it, so story mode never shows one.
# Adding it here lets the shuffle use it; its orders are gated by the recipe patcher
# like any other character's, falling back to the Random meal if they all lock out.
EXTRA_POOL_CHARACTERS: frozenset[str] = frozenset({"Alien"})

# Story level number (1-based) -> the <Customer> pool that level draws from.
# Taken from the first 120 `<Level id="">` entries in Game.xml, in order; the
# entries after those belong to the non-story stages (9 and up).
STORY_LEVEL_CUSTOMER_IDS: tuple[str, ...] = (
    "customers1-1a", "customers1-1b", "customers1-1c", "customers1-2a",
    "customers1-2b", "customers1-2c", "customers1-3a", "customers1-3b",
    "customers1-3c", "customers1-4a", "customers1-4b", "customers1-4c",
    "customers1-5a", "customers1-5b", "customers1-5c", "customers2ALT-1a",
    "customers2ALT-1b", "customers2ALT-1c", "customers2ALT-2a", "customers2ALT-2b",
    "customers2ALT-2c", "customers2ALT-3a", "customers2ALT-3b", "customers2ALT-3c",
    "customers2ALT-4a", "customers2ALT-4b", "customers2ALT-4c", "customers2ALT-5a",
    "customers2ALT-5b", "customers2ALT-5c", "customers2-1a", "customers2-1b",
    "customers2-1c", "customers2-2a", "customers2-2b", "customers2-2c",
    "customers2-3a", "customers2-3b", "customers2-3c", "customers2-4a",
    "customers2-4b", "customers2-4c", "customers2-5a", "customers2-5b",
    "customers2-5c", "customers3-1a", "customers3-1b", "customers3-1c",
    "customers3-2a", "customers3-2b", "customers3-2c", "customers3-3a",
    "customers3-3b", "customers3-3c", "customers3-4a", "customers3-4b",
    "customers3-4c", "customers3-5a", "customers3-5b", "customers3-5c",
    "customers4-1a", "customers4-1b", "customers4-1c", "customers4-2a",
    "customers4-2b", "customers4-2c", "customers4-3a", "customers4-3b",
    "customers4-3c", "customers4-4a", "customers4-4b", "customers4-4c",
    "customers4-5a", "customers4-5b", "customers4-5c", "customers5-1a",
    "customers5-1b", "customers5-1c", "customers5-2a", "customers5-2b",
    "customers5-2c", "customers5-3a", "customers5-3b", "customers5-3c",
    "customers5-4a", "customers5-4b", "customers5-4c", "customers5-5a",
    "customers5-5b", "customers5-5c", "customers6-1a", "customers6-1b",
    "customers6-1c", "customers6-2a", "customers6-2b", "customers6-2c",
    "customers6-3a", "customers6-3b", "customers6-3c", "customers6-4a",
    "customers6-4b", "customers6-4c", "customers6-5a", "customers6-5b",
    "customers6-5c", "customers7-1a", "customers7-1b", "customers7-1c",
    "customers7-2a", "customers7-2b", "customers7-2c", "customers7-3a",
    "customers7-3b", "customers7-3c", "customers7-4a", "customers7-4b",
    "customers7-4c", "customers7-5a", "customers7-5b", "customers7-5c",
)

# <Customer> id -> ((count, character), ...) exactly as the vanilla file defines it,
# in file order.  Order matters: the shuffle walks this mapping, so changing it
# changes every seed's result.
VANILLA_CUSTOMERS: dict[str, tuple[tuple[int, str], ...]] = {
    "customers1-1a": ((7, "Random"),),
    "customers1-1b": ((9, "Random"),),
    "customers1-1c": ((9, "Random"),),
    "customers1-2a": ((9, "Random"),),
    "customers1-2b": ((10, "Random"),),
    "customers1-2c": ((10, "Random"),),
    "customers1-3a": ((5, "Random"), (5, "BizChick"),),
    "customers1-3b": ((5, "Random"), (5, "BizChick"),),
    "customers1-3c": ((5, "Random"), (6, "BizChick"),),
    "customers1-4a": ((5, "Random"), (4, "OldChap"), (3, "BizChick"),),
    "customers1-4b": ((5, "Random"), (4, "OldChap"), (3, "BizChick"),),
    "customers1-4c": ((4, "Random"), (4, "OldChap"), (4, "BizChick"),),
    "customers1-5a": ((4, "Mimic"), (6, "Random"), (3, "BizChick"),),
    "customers1-5b": ((4, "Mimic"), (6, "Random"), (3, "BizChick"),),
    "customers1-5c": ((4, "Random"), (3, "Mimic"), (3, "OldChap"), (4, "BizChick"),),
    "customers2ALT-1a": ((4, "DogBag"), (5, "BizChick"), (5, "Random"),),
    "customers2ALT-1b": ((4, "DogBag"), (5, "Random"), (3, "OldChap"), (2, "Mimic"),),
    "customers2ALT-1c": ((5, "DogBag"), (9, "Random"),),
    "customers2ALT-2a": ((6, "Skater"), (6, "Random"), (4, "BizChick"),),
    "customers2ALT-2b": ((6, "Skater"), (4, "BizChick"), (3, "DogBag"), (3, "OldChap"),),
    "customers2ALT-2c": ((6, "Skater"), (6, "Random"), (2, "Mimic"), (2, "DogBag"),),
    "customers2ALT-3a": ((4, "DogBag"), (3, "Mimic"), (2, "OldChap"), (3, "Random"), (2, "BizChick"),),
    "customers2ALT-3b": ((4, "DogBag"), (3, "Mimic"), (4, "Random"), (3, "BizChick"),),
    "customers2ALT-3c": ((7, "Skater"), (9, "Random"),),
    "customers2ALT-4a": ((3, "Skater"), (4, "Random"), (3, "BizChick"), (2, "Mimic"), (2, "DogBag"),),
    "customers2ALT-4b": ((5, "Random"), (5, "DogBag"), (4, "Mimic"),),
    "customers2ALT-4c": ((8, "BizChick"), (3, "Skater"), (3, "DogBag"),),
    "customers2ALT-5a": (
        (2, "Skater"),
        (2, "DogBag"),
        (3, "BizChick"),
        (3, "Random"),
        (2, "Mimic"),
        (2, "OldChap"),
    ),
    "customers2ALT-5b": (
        (2, "Skater"),
        (2, "DogBag"),
        (3, "BizChick"),
        (3, "Random"),
        (2, "Mimic"),
        (2, "OldChap"),
    ),
    "customers2ALT-5c": (
        (2, "Skater"),
        (2, "DogBag"),
        (3, "BizChick"),
        (3, "Random"),
        (2, "Mimic"),
        (2, "OldChap"),
    ),
    "customers2-1a": ((5, "Cowboy"), (4, "BizChick"), (5, "Random"),),
    "customers2-1b": ((7, "Cowboy"), (7, "Random"),),
    "customers2-1c": ((4, "Cowboy"), (4, "OldChap"), (6, "Random"),),
    "customers2-2a": ((4, "Cowboy"), (3, "Mimic"), (2, "OldChap"), (3, "Random"), (2, "BizChick"),),
    "customers2-2b": ((4, "Cowboy"), (3, "Mimic"), (4, "Random"), (3, "BizChick"),),
    "customers2-2c": ((5, "Cowboy"), (9, "Random"),),
    "customers2-3a": ((5, "Cowgirl"), (4, "Cowboy"), (5, "Random"),),
    "customers2-3b": ((5, "Cowgirl"), (4, "BizChick"), (3, "Mimic"), (4, "DogBag"),),
    "customers2-3c": ((4, "Cowgirl"), (2, "Skater"), (3, "BizChick"), (2, "Mimic"), (3, "OldChap"),),
    "customers2-4a": ((5, "Cowgirl"), (6, "Skater"), (5, "Cowboy"),),
    "customers2-4b": ((7, "Cowgirl"), (7, "Random"),),
    "customers2-4c": ((4, "Cowgirl"), (4, "Cowboy"), (2, "Random"), (2, "BizChick"), (2, "OldChap"),),
    "customers2-5a": (
        (2, "Cowboy"),
        (2, "Cowgirl"),
        (2, "Skater"),
        (3, "DogBag"),
        (2, "BizChick"),
        (2, "Random"),
        (2, "Mimic"),
        (3, "OldChap"),
    ),
    "customers2-5b": (
        (2, "Cowboy"),
        (2, "Cowgirl"),
        (2, "Skater"),
        (3, "DogBag"),
        (2, "BizChick"),
        (2, "Random"),
        (2, "Mimic"),
        (3, "OldChap"),
    ),
    "customers2-5c": (
        (2, "Cowboy"),
        (2, "Cowgirl"),
        (2, "Skater"),
        (3, "DogBag"),
        (2, "BizChick"),
        (2, "Random"),
        (2, "Mimic"),
        (3, "OldChap"),
    ),
    "customers3-1a": ((5, "BizDude"), (3, "Random"), (3, "BizChick"), (3, "Cowgirl"),),
    "customers3-1b": ((5, "BizDude"), (4, "Random"), (2, "Cowboy"), (3, "DogBag"),),
    "customers3-1c": ((5, "BizDude"), (4, "Random"), (4, "Skater"), (3, "OldChap"),),
    "customers3-2a": ((5, "Punk"), (3, "OldChap"), (3, "Cowboy"), (3, "Mimic"),),
    "customers3-2b": ((4, "Punk"), (3, "DogBag"), (2, "BizChick"), (3, "Random"), (4, "Skater"),),
    "customers3-2c": ((7, "Punk"), (7, "Random"),),
    "customers3-3a": ((3, "BizDude"), (3, "Mimic"), (4, "BizChick"), (4, "Cowboy"),),
    "customers3-3b": ((2, "Punk"), (3, "BizDude"), (4, "Skater"), (5, "Random"), (2, "Cowgirl"),),
    "customers3-3c": ((4, "Punk"), (5, "BizDude"), (5, "BizChick"),),
    "customers3-4a": ((2, "Punk"), (4, "BizDude"), (2, "Cowgirl"), (3, "DogBag"), (3, "OldChap"),),
    "customers3-4b": ((3, "Punk"), (3, "BizDude"), (4, "Cowboy"), (4, "Random"),),
    "customers3-4c": ((3, "Punk"), (3, "BizDude"), (2, "Cowboy"), (3, "BizChick"), (3, "Cowgirl"),),
    "customers3-5a": (
        (2, "Punk"),
        (2, "BizDude"),
        (2, "Cowboy"),
        (2, "Cowgirl"),
        (2, "Skater"),
        (2, "Random"),
        (2, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (2, "OldChap"),
    ),
    "customers3-5b": (
        (2, "Punk"),
        (2, "BizDude"),
        (2, "Cowboy"),
        (2, "Cowgirl"),
        (2, "Skater"),
        (2, "Random"),
        (2, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (2, "OldChap"),
    ),
    "customers3-5c": (
        (2, "Punk"),
        (2, "BizDude"),
        (2, "Cowboy"),
        (2, "Cowgirl"),
        (2, "Skater"),
        (2, "Random"),
        (2, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (2, "OldChap"),
    ),
    "customers4-1a": ((5, "Clown"), (5, "Random"), (4, "BizChick"),),
    "customers4-1b": ((5, "Clown"), (3, "BizChick"), (3, "BizDude"), (3, "Cowboy"), (2, "Skater"),),
    "customers4-1c": ((5, "Clown"), (3, "DogBag"), (2, "OldChap"), (2, "Cowboy"), (2, "Punk"),),
    "customers4-2a": ((5, "SchoolGirls"), (2, "Cowboy"), (3, "Cowgirl"), (2, "Mimic"), (2, "BizChick"),),
    "customers4-2b": ((5, "SchoolGirls"), (5, "Clown"), (8, "Skater"),),
    "customers4-2c": ((7, "SchoolGirls"), (7, "Random"),),
    "customers4-3a": ((5, "MomAndKid"), (3, "DogBag"), (2, "BizChick"), (2, "Cowgirl"), (2, "SchoolGirls"),),
    "customers4-3b": ((5, "MomAndKid"), (5, "Random"), (8, "Skater"),),
    "customers4-3c": ((5, "MomAndKid"), (2, "Mimic"), (3, "OldChap"), (2, "Clown"), (2, "SchoolGirls"),),
    "customers4-4a": ((3, "MomAndKid"), (3, "Clown"), (2, "SchoolGirls"), (6, "Random"),),
    "customers4-4b": ((5, "MomAndKid"), (5, "Clown"), (4, "SchoolGirls"),),
    "customers4-4c": (
        (2, "MomAndKid"),
        (2, "Clown"),
        (2, "SchoolGirls"),
        (3, "Mimic"),
        (3, "BizDude"),
        (2, "BizChick"),
    ),
    "customers4-5a": (
        (2, "MomAndKid"),
        (2, "Clown"),
        (2, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (2, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (2, "OldChap"),
    ),
    "customers4-5b": (
        (2, "MomAndKid"),
        (2, "Clown"),
        (2, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (2, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (2, "OldChap"),
    ),
    "customers4-5c": (
        (2, "MomAndKid"),
        (2, "Clown"),
        (2, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (2, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (2, "OldChap"),
    ),
    "customers5-1a": ((5, "SportsFan"), (5, "Random"), (3, "BizDude"), (3, "Skater"),),
    "customers5-1b": ((5, "SportsFan"), (3, "SchoolGirls"), (3, "Punk"), (4, "BizChick"),),
    "customers5-1c": ((5, "SportsFan"), (3, "DogBag"), (2, "MomAndKid"), (2, "Cowboy"), (2, "BizDude"),),
    "customers5-2a": ((5, "SoftballPlayer"), (4, "SportsFan"), (5, "Random"),),
    "customers5-2b": ((7, "SoftballPlayer"), (4, "Random"), (3, "Cowboy"),),
    "customers5-2c": ((5, "SoftballPlayer"), (2, "Mimic"), (3, "OldChap"), (4, "Punk"),),
    "customers5-3a": ((5, "Annoying"), (3, "OldChap"), (2, "DogBag"), (4, "Random"),),
    "customers5-3b": ((5, "Annoying"), (5, "Clown"), (4, "SportsFan"),),
    "customers5-3c": ((5, "Annoying"), (6, "Skater"), (3, "Cowboy"), (2, "Cowgirl"),),
    "customers5-4a": (
        (3, "Annoying"),
        (3, "SoftballPlayer"),
        (2, "SportsFan"),
        (2, "DogBag"),
        (2, "OldChap"),
        (4, "Skater"),
    ),
    "customers5-4b": ((9, "SportsFan"), (5, "SchoolGirls"),),
    "customers5-4c": ((5, "Annoying"), (5, "BizDude"), (4, "Punk"),),
    "customers5-5a": (
        (3, "SportsFan"),
        (2, "SoftballPlayer"),
        (3, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers5-5b": (
        (2, "SportsFan"),
        (3, "SoftballPlayer"),
        (3, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers5-5c": (
        (3, "SportsFan"),
        (2, "SoftballPlayer"),
        (3, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers6-1a": ((7, "Hippy"), (7, "Random"),),
    "customers6-1b": ((5, "Hippy"), (2, "BizDude"), (2, "SchoolGirls"), (3, "DogBag"), (2, "Cowboy"),),
    "customers6-1c": ((7, "Hippy"), (5, "Skater"), (3, "OldChap"),),
    "customers6-2a": ((6, "Surfer"), (3, "Annoying"), (3, "BizDude"), (2, "Punk"),),
    "customers6-2b": ((6, "Surfer"), (4, "Random"), (4, "Mimic"),),
    "customers6-2c": ((5, "Surfer"), (5, "SoftballPlayer"), (4, "SportsFan"),),
    "customers6-3a": ((4, "Surfer"), (4, "Hippy"), (3, "MomAndKid"), (3, "SoftballPlayer"),),
    "customers6-3b": ((4, "Surfer"), (4, "Hippy"), (3, "Mimic"), (3, "Cowgirl"),),
    "customers6-3c": ((4, "Surfer"), (4, "Hippy"), (3, "SchoolGirls"), (3, "BizChick"),),
    "customers6-4a": ((4, "Surfer"), (4, "Hippy"), (3, "Random"), (3, "Annoying"),),
    "customers6-4b": ((4, "Surfer"), (4, "Hippy"), (3, "BizDude"), (3, "Cowboy"),),
    "customers6-4c": ((4, "Surfer"), (4, "Hippy"), (2, "Cowboy"), (2, "SportsFan"), (2, "DogBag"),),
    "customers6-5a": (
        (4, "Surfer"),
        (4, "Hippy"),
        (1, "SportsFan"),
        (1, "SoftballPlayer"),
        (1, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers6-5b": (
        (4, "Surfer"),
        (4, "Hippy"),
        (1, "SportsFan"),
        (1, "SoftballPlayer"),
        (1, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers6-5c": (
        (4, "Surfer"),
        (4, "Hippy"),
        (1, "SportsFan"),
        (1, "SoftballPlayer"),
        (1, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers7-1a": ((5, "Sumo"), (5, "Random"), (4, "BizChick"),),
    "customers7-1b": ((5, "Sumo"), (4, "Cowboy"), (5, "Cowgirl"),),
    "customers7-1c": ((5, "Sumo"), (4, "BizDude"), (5, "BizChick"),),
    "customers7-2a": ((5, "Sumo"), (5, "Punk"), (8, "Skater"),),
    "customers7-2b": ((5, "Sumo"), (2, "SchoolGirls"), (2, "OldChap"), (3, "DogBag"), (2, "Surfer"),),
    "customers7-2c": ((5, "Sumo"), (2, "Mimic"), (3, "Hippy"), (2, "Annoying"), (4, "Skater"),),
    "customers7-3a": ((5, "Ninja"), (5, "Random"), (4, "SoftballPlayer"),),
    "customers7-3b": ((5, "Ninja"), (4, "BizDude"), (2, "MomAndKid"), (3, "DogBag"),),
    "customers7-3c": ((5, "Ninja"), (8, "Skater"), (5, "SchoolGirls"),),
    "customers7-4a": ((5, "Sumo"), (5, "Ninja"), (2, "Clown"), (2, "Annoying"),),
    "customers7-4b": ((5, "Sumo"), (5, "Ninja"), (2, "Clown"), (2, "BizChick"),),
    "customers7-4c": ((5, "Sumo"), (5, "Ninja"), (2, "Clown"), (2, "Cowboy"),),
    "customers7-5a": (
        (3, "Sumo"),
        (3, "Ninja"),
        (1, "Surfer"),
        (1, "Hippy"),
        (1, "SportsFan"),
        (1, "SoftballPlayer"),
        (1, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers7-5b": (
        (3, "Sumo"),
        (3, "Ninja"),
        (1, "Surfer"),
        (1, "Hippy"),
        (1, "SportsFan"),
        (1, "SoftballPlayer"),
        (1, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "customers7-5c": (
        (3, "Sumo"),
        (3, "Ninja"),
        (1, "Surfer"),
        (1, "Hippy"),
        (1, "SportsFan"),
        (1, "SoftballPlayer"),
        (1, "Annoying"),
        (1, "MomAndKid"),
        (1, "Clown"),
        (1, "SchoolGirls"),
        (1, "Punk"),
        (1, "BizDude"),
        (1, "Cowboy"),
        (1, "Cowgirl"),
        (1, "Skater"),
        (1, "Random"),
        (1, "DogBag"),
        (1, "BizChick"),
        (1, "Mimic"),
        (1, "OldChap"),
    ),
    "relax1": ((10, "Random"), (10, "BizChick"), (4, "Mimic"),),
    "relax2": ((8, "Random"), (8, "BizChick"), (3, "Mimic"), (8, "Skater"),),
    "relax3": ((4, "Random"), (4, "BizChick"), (4, "Mimic"), (4, "Skater"), (4, "Cowboy"), (4, "Cowgirl"),),
    "relax4": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
    ),
    "relax5": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
    ),
    "relax6": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
        (4, "SportsFan"),
        (4, "SoftballPlayer"),
    ),
    "relax7": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
        (4, "SportsFan"),
        (4, "SoftballPlayer"),
        (4, "Hippy"),
        (4, "Surfer"),
    ),
    "relax8": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
        (4, "SportsFan"),
        (4, "SoftballPlayer"),
        (4, "Hippy"),
        (4, "Surfer"),
        (4, "Sumo"),
        (4, "Ninja"),
    ),
    "challenge1": ((10, "Random"), (10, "BizChick"), (4, "Mimic"),),
    "challenge2": ((8, "Random"), (8, "BizChick"), (3, "Mimic"), (8, "Skater"),),
    "challenge3": ((4, "Random"), (4, "BizChick"), (4, "Mimic"), (4, "Skater"), (4, "Cowboy"), (4, "Cowgirl"),),
    "challenge4": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
    ),
    "challenge5": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
    ),
    "challenge6": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
        (4, "SportsFan"),
        (4, "SoftballPlayer"),
    ),
    "challenge7": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
        (4, "SportsFan"),
        (4, "SoftballPlayer"),
        (4, "Hippy"),
        (4, "Surfer"),
    ),
    "challenge8": (
        (4, "Random"),
        (4, "BizChick"),
        (4, "Mimic"),
        (4, "Skater"),
        (4, "Cowboy"),
        (4, "Cowgirl"),
        (4, "BizDude"),
        (4, "Punk"),
        (4, "Clown"),
        (4, "SchoolGirls"),
        (4, "MomAndKid"),
        (4, "SportsFan"),
        (4, "SoftballPlayer"),
        (4, "Hippy"),
        (4, "Surfer"),
        (4, "Sumo"),
        (4, "Ninja"),
    ),
}
